version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/estoque_db
      - SPRING_DATASOURCE_USERNAME=estoque_user
      - SPRING_DATASOURCE_PASSWORD=estoque123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=20000
      - SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT=300000
      - SPRING_DATASOURCE_HIKARI_MAX_LIFETIME=1800000
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=UTC
      - IA_SERVICE_URL=http://ia:5000/sugestao
    depends_on:
      - db
      - ia

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=estoque123
      - MYSQL_DATABASE=estoque_db
      - MYSQL_USER=estoque_user
      - MYSQL_PASSWORD=estoque123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  ia:
    build:
      context: ./ia-microservice
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=estoque_db
      - MYSQL_USER=estoque_user
      - MYSQL_PASSWORD=estoque123
      - MYSQL_PORT=3306
    depends_on:
      - db

volumes:
  db_data: