spring:
  profiles:
    active: dev
    
  datasource:
    url: jdbc:mysql://localhost:3306/estoque_ia
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop # Recria o banco a cada execução
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    com.estoqueia: DEBUG
    org.springframework.security: INFO